### ISSUE TITLE
version composer.json

### ISSUE THREAD

**Issue by xvlady** [avto-dev/app-version-laravel#2]
добрый день.
Не могли бы вы добвить в описание почему не используется version из composer.json, а используется дополнительная переменная?

**Comment by tarampampam** [comment]
Каким образом для отдельно-стоящего приложения вы бы хранили в `composer.json` значение версии приложения? Для VCS верный путь - это версионирование с помощью тегов (https://getcomposer.org/doc/articles/versions.md#versions-and-constraints).

Хардкодить значение версии в `composer.json` - это совсем не лучшая идея. Более того - править его средствами приложения (изменение номера билда) - совсем плохая идея.

После установки зависимостей и генерирования `autoloader` вы можете вообще смело удалить `composer.json` + `composer.lock` - всё должно работать без каких-либо проблем. Ваш подход лишил бы приложение данной гибкости.

Именно в связи с этими ограничениями (их можно привести значительно большее количество) - используется отдельный пакет, который отвечает за данный функционал.
