### ISSUE TITLE
Не отрабатывает afterResolving

### ISSUE THREAD

**Issue by dotzero** [avto-dev/app-version-laravel#3]
### Системная информация:

 * Версия PHP: `v7.2`
 * Версия данного пакета: `v1.3`
 * Версия пакета Laravel: `v5.4`

### Ошибка

После установки данного пакета перестает отрабатывать такой код:
```
$this->app->afterResolving('blade.compiler', function (BladeCompiler $bladeCompiler) {
   // ...
});
```
Он используется в пакете `spatie/laravel-permission`

https://github.com/spatie/laravel-permission/blob/1.17.0/src/PermissionServiceProvider.php

**Comment by tarampampam** [comment]
Т.е. при добавлении в `composer.json` проекта:

```json
{
    "extra": {
        "laravel": {
            "dont-discover": [
                "avto-dev/app-version-laravel",
            ]
        }
    }
}
```

И выполнении `php artisan package:discover` работоспособность возвращается?

**Comment by dotzero** [comment]
Все правильно, кроме того, если заменить 
```
$blade = $this->app->make('view')->getEngineResolver()->resolve('blade')->getCompiler();
```
в файле https://github.com/avto-dev/app-version-laravel/blob/master/src/AppVersionServiceProvider.php на
```
$this->app->afterResolving('blade.compiler', function (BladeCompiler $bladeCompiler) {
   // ...
});
```
то тоже все работает хорошо.

**Comment by tarampampam** [comment]
@dotzero https://github.com/avto-dev/app-version-laravel/releases/tag/v1.3.1

Могу закрывать issue?
